from __future__ import annotations

from typing import Any, TypedDict

from ..models import CropCase, SymbioEnvelope, utc_now
from ..settings import settings
from .base import AgentBase


class ReportState(TypedDict, total=False):
    case: dict[str, Any]
    vision: dict[str, Any]
    agronomy: dict[str, Any]
    rules: dict[str, Any]
    audit: dict[str, Any]
    report: dict[str, Any]
    framework_trace: list[str]


class OperationsReportAgent(AgentBase):
    """Final report agent implemented as a LangGraph-style graph."""

    name = "Operations_Report_Agent"
    role = "langgraph_operations_and_audit_packet"

    async def run(self, *, case: CropCase, events: list[dict[str, Any]], shared: dict[str, Any]) -> SymbioEnvelope:
        state: ReportState = {
            "case": case.to_dict(),
            "vision": shared.get("vision", {}),
            "agronomy": shared.get("agronomy", {}),
            "rules": shared.get("rules", {}),
            "audit": shared.get("audit", {}),
            "framework_trace": [],
        }
        report, framework_runtime = self._run_report_graph(state, events)
        shared["report"] = report
        shared["operation_graph"] = {
            "framework": framework_runtime,
            "nodes": report.get("framework_trace", []),
            "why_it_matters": "This worker is implemented as a graph agent, while upstream workers are custom Python agents. Band is the bridge between runtimes.",
        }
        case.final_report = report
        requires_review = bool(report.get("human_review_required"))
        case.status = "human_review_required" if requires_review else "complete"
        case.risk_level = report.get("risk_level", "low")
        case.requires_human_review = requires_review
        finding = "Final packet generated by LangGraph report agent; human approval is required before irreversible action." if requires_review else "Final packet generated by LangGraph report agent; only low-risk actions recommended."
        
        return SymbioEnvelope(
            case_id=case.case_id,
            agent=self.name,
            role=self.role,
            task_state=case.status,
            finding=finding,
            confidence=0.95,
            risk_level=case.risk_level,
            requires_human_review=requires_review,
            next_agent="Human_Reviewer",
            handoff_reason="Human reviewer receives the final audit packet and approves or rejects high-risk physical-world actions.",
            input_refs=self.last_event_ids(events, 5),
            payload=report,
        )

    def _run_report_graph(self, state: ReportState, events: list[dict[str, Any]]) -> tuple[dict[str, Any], str]:
        if not settings.langgraph_force_fallback:
            try:
                from langgraph.graph import END, START, StateGraph  # type: ignore

                graph = StateGraph(ReportState)
                graph.add_node("summarize_case", lambda s: self._node_summarize_case(s, events))
                graph.add_node("business_impact", self._node_business_impact)
                graph.add_node("human_gate", self._node_human_gate)
                graph.add_edge(START, "summarize_case")
                graph.add_edge("summarize_case", "business_impact")
                graph.add_edge("business_impact", "human_gate")
                graph.add_edge("human_gate", END)
                compiled = graph.compile()
                result = compiled.invoke(state)
                report = result.get("report", {})
                report["framework"] = "LangGraph StateGraph"
                report["framework_runtime"] = "langgraph"
                return report, "LangGraph StateGraph"
            except Exception as exc:
                fallback_state = self._run_fallback_graph(state, events)
                report = fallback_state.get("report", {})
                report["framework"] = "LangGraph-compatible fallback graph"
                report["framework_runtime"] = "fallback_graph"
                report["framework_warning"] = f"LangGraph not available or failed: {exc.__class__.__name__}: {str(exc)[:180]}"
                return report, "LangGraph-compatible fallback graph"

        fallback_state = self._run_fallback_graph(state, events)
        report = fallback_state.get("report", {})
        report["framework"] = "LangGraph-compatible fallback graph"
        report["framework_runtime"] = "fallback_graph"
        return report, "LangGraph-compatible fallback graph"

    def _run_fallback_graph(self, state: ReportState, events: list[dict[str, Any]]) -> ReportState:
        state.update(self._node_summarize_case(state, events))
        state.update(self._node_business_impact(state))
        state.update(self._node_human_gate(state))
        return state

    def _node_summarize_case(self, state: ReportState, events: list[dict[str, Any]]) -> ReportState:
        case = state.get("case", {})
        rules = state.get("rules", {})
        vision = state.get("vision", {})
        agronomy = state.get("agronomy", {})
        audit = state.get("audit", {})
        top = (vision.get("top_hypotheses") or [{}])[0]
        requires_review = bool(rules.get("requires_human_review", False))
        blocked = rules.get("blocked_actions", [])
        allowed = rules.get("allowed_actions", []) or agronomy.get("recommended_actions", [])
        trace = list(state.get("framework_trace", [])) + ["summarize_case"]
        report = {
            "case_id": case.get("case_id", "unknown"),
            "generated_at": utc_now(),
            "executive_summary": (
                f"Symbio.AI triaged {case.get('crop', 'crop')} incident in {case.get('location', 'unknown')}. "
                f"Top hypothesis: {top.get('condition', 'unknown')} ({top.get('confidence', 0):.2f}). "
                f"Risk: {rules.get('risk_level', 'unknown')}. Human review required: {requires_review}."
            ),
            "risk_level": rules.get("risk_level", "unknown"),
            "top_hypothesis": top,
            "vision": vision,
            "agronomy_evidence": agronomy.get("evidence", []),
            "recommended_actions": allowed,
            "blocked_actions": blocked,
            "triggered_rules": rules.get("triggered_rules", []),
            "audit_summary": audit.get("audit_summary", "No auditor intercept required."),
            "human_review_required": requires_review,
            "human_review_status": "pending" if requires_review else "not_required",
            "band_handoffs": [e.get("event_id") for e in events],
            "framework_trace": trace,
            "disclaimer": "Prototype for workflow coordination. Not agronomic, legal, or regulatory advice.",
        }
        return {"report": report, "framework_trace": trace}

    def _node_business_impact(self, state: ReportState) -> ReportState:
        report = dict(state.get("report", {}))
        case = state.get("case", {})
        rules = state.get("rules", {})
        urgency = case.get("urgency", "medium")
        acreage = float(case.get("acreage", 0.0) or 0.0)
        risk = rules.get("risk_level", "low")
        inspection_window = "24 hours" if urgency == "high" or risk in {"high", "critical"} else "72 hours"
        report["business_impact"] = {
            "inspection_window": inspection_window,
            "estimated_scope": "plot-level" if acreage < 2 else "multi-plot / cooperative-level",
            "insurance_packet_needed": risk in {"high", "critical"},
            "supply_chain_hold": risk in {"high", "critical"} and acreage >= 2,
        }
        trace = list(state.get("framework_trace", [])) + ["business_impact"]
        report["framework_trace"] = trace
        return {"report": report, "framework_trace": trace}

    def _node_human_gate(self, state: ReportState) -> ReportState:
        report = dict(state.get("report", {}))
        requires_review = bool(report.get("human_review_required"))
        report["decision_gate"] = {
            "autonomous_actions_allowed": not requires_review,
            "irreversible_actions_blocked": requires_review,
            "human_reviewer_target": "Human_Reviewer",
            "gate_reason": "Symbolic rules or risk score require human approval." if requires_review else "No high-risk symbolic rule fired.",
        }
        trace = list(state.get("framework_trace", [])) + ["human_gate"]
        report["framework_trace"] = trace
        return {"report": report, "framework_trace": trace}